OCC/Controllers/AjaxController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Services;

namespace OCC.Controllers
{
    public class AjaxController : Controller
    {
        #region constructor
        private readonly IValidateService _validateService;
        private readonly IGuestService _guestService;
        private readonly ISerializeService _serializeService;

        public AjaxController(IValidateService validateService, IGuestService guestService, 
            ISerializeService serializeService)
        {
            _validateService = validateService;
            _guestService = guestService;
            _serializeService = serializeService;
        }
        #endregion

        [HttpPost]
        public JsonResult ValidateNameSurname(string name, string surname)
        {
            var serviceResult = _validateService.IsGuestInDb(name, surname);
            return Json(serviceResult);
        }

        [HttpPost]
        public JsonResult ChangeStatus(int guestId, string newStatus)
        {
            _guestService.ChangeStatus(guestId, newStatus);
            return null;
        }

        public JsonResult SaveAllGuests()
        {
            var path = Server.MapPath("~/SerializedData");
            var savePath = _serializeService.SerializeFullGuestList(path);

            return Json(savePath);
        }

        public JsonResult SaveAttendingGuests()
        {
            var path = Server.MapPath("~/SerializedData");
            var savePath = _serializeService.SerializeAttendingGuestList(path);

            return Json(savePath);
        }
      
    }
}

OCC/Controllers/GuestController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Services;
using Models.DataTransferObjects;
using Models;

namespace OCC.Controllers
{
    public class GuestController : Controller
    {
        #region constructor
        private readonly IGuestService _guestService;

        public GuestController(IGuestService guestService)
        {
            _guestService = guestService;
        }
        #endregion

        public ActionResult Index()
        {
            var guestList = _guestService.GetGuestList();

            return View("Index", guestList);
        }

        public ActionResult Create()
        {
            return View("Create");
        }

        [HttpPost]
        public ActionResult Create(GuestDTO guest)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    _guestService.AddGuest(guest);
                }

                return RedirectToAction("Index");
            }
            catch
            {
                return View("Create");
            }
        }

        public ActionResult Edit(int id)
        {
            var guest = _guestService.GetGuest(id);

            return View("Edit", guest);
        }

        [HttpPost]
        public ActionResult Edit(Guest editedGuest)
        {
            try
            {
                _guestService.EditGuest(editedGuest);

                return RedirectToAction("Index");
            }
            catch
            {
                return View("Edit");
            }
        }

        public ActionResult Delete(int id)
        {
            _guestService.DeleteGuest(id);

            return RedirectToAction("Index");
        }

        public ActionResult GenderBalance()
        {
            var genderBalanceViewModel = _guestService.GetGenderBalanceViewModel();
            return PartialView("_genderBalance", genderBalanceViewModel);
        }

    }
}

OCC/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Services;

namespace OCC.Controllers
{
    public class HomeController : Controller
    {
        #region constructor
        private readonly ISerializeService _serializeService;

        public HomeController(ISerializeService serializeService)
        {            
            _serializeService = serializeService;
        }
        #endregion

        public ActionResult Index()
        {
            return View("Index");
        }

        public ActionResult Refresh()
        {            
            return Redirect(HttpContext.Request.UrlReferrer.AbsoluteUri);
        }
      
        public ActionResult LoadAllGuests()
        {
            var path = Server.MapPath("~/SerializedData");
            var isLoadSuccessful = _serializeService.DeserializeFullGuestList(path);
            
            if (isLoadSuccessful == false)
            {
                return View("FailedLoad");
            }

            return RedirectToAction("Index");
        }
    }
}

OCC/Views/Guest/Create.cshtml
@model Models.DataTransferObjects.GuestDTO

@{
    ViewBag.Title = "Create Guest";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2 class="ui header">Create</h2>

<div class="ui negative message" hidden="hidden" id="ErrorMessage">
    <i class="close icon" id="CloseErrorMessage"></i>
    <div class="header">
        There is a trouble with your request
    </div>
    <p id="ErrorMessageText"></p>
</div>

<form class="ui form" id="CreateGuestForm" action="/Guest/Create" method="post">
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)
    <h4 class="ui dividing header">Personal Information</h4>
    <div class="two fields">
        <div class="field">
            <label>Name</label>
            <div class="two fields">
                <div class="field">
                    @Html.TextBoxFor(model => model.Name, new { @placeholder = "Name" })
                    @Html.ValidationMessageFor(model => model.Name)
                </div>
                <div class="field">
                    @Html.TextBoxFor(model => model.Surname, new { @placeholder = "Surname" })
                    @Html.ValidationMessageFor(model => model.Surname)
                </div>
            </div>
        </div>
        <div class="field">
            <label>Gender</label>
            @Html.EnumDropDownListFor(model => model.Gender, new { @class = "ui selection dropdown" })
            @Html.ValidationMessageFor(model => model.Gender)
        </div>
    </div>    
    <input type="submit" value="Create" class="ui button"/>
</form>    

    @section Scripts {
        @Scripts.Render("~/bundles/jqueryval")
        <script src="~/Scripts/Developer/GuestCreate.js"></script>
    }

OCC/Views/Guest/Edit.cshtml
@model Models.Guest

@{
    ViewBag.Title = "Guest Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2 class="ui header">Edit</h2>

<div class="ui negative message" hidden="hidden" id="ErrorMessage">
    <i class="close icon" id="CloseErrorMessage"></i>
    <div class="header">
        There is a trouble with your request
    </div>
    <p id="ErrorMessageText"></p>
</div>

<form class="ui form" id="EditGuestForm" action="/Guest/Edit" method="post">
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)
    @Html.HiddenFor(model => model.Id)
    <h4 class="ui dividing header">Personal Information</h4>
    <div class="two fields">
        <div class="field">
            <label>Name</label>
            <div class="two fields">
                <div class="field">
                    @Html.TextBoxFor(model => model.Name, new { @placeholder = "Name" })
                    @Html.ValidationMessageFor(model => model.Name)
                </div>
                <div class="field">
                    @Html.TextBoxFor(model => model.Surname, new { @placeholder = "Surname" })
                    @Html.ValidationMessageFor(model => model.Surname)
                </div>
            </div>
        </div>
        <div class="field">
            <label>Gender</label>
            @Html.EnumDropDownListFor(model => model.Gender, new { @class = "ui selection dropdown" })
            @Html.ValidationMessageFor(model => model.Gender)
        </div>
    </div>
    <input type="submit" value="Create" class="ui button" />
</form>



@*@using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            <h4>Guest</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            @Html.HiddenFor(model => model.Id)

            <div class="form-group">
                @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Surname, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Surname, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Surname, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Save" class="btn btn-default" />
                </div>
            </div>
        </div>
    }*@


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")

    <script src="~/Scripts/Developer/GuestEdit.js"></script>
}

OCC/Views/Guest/GenderBalance.cshtml
@model Models.ViewModels.GenderBalanceViewModel

<div>
    <h4>GenderBalanceViewModel</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.MenInvited)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MenInvited)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.WomenInvited)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.WomenInvited)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MenAttending)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MenAttending)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.WomenAttending)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.WomenAttending)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.InvitedWarning)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.InvitedWarning)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AttendingWarning)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AttendingWarning)
        </dd>

    </dl>
</div>

OCC/Views/Guest/Index.cshtml
@using Models;
@using System.Web.Mvc.Html;
@model List<Guest>

    @{
        ViewBag.Title = "Guest List";
        Layout = "~/Views/Shared/_Layout.cshtml";
    }

    <h2 class="ui header">Guest List</h2>    
    <div class="ui cards">

        @foreach(Guest guest in Model)
        {
          @Html.Partial("_guestCard", guest);
        }
        
    </div>
        

    @section scripts
{
        <script src="~/Scripts/Developer/GuestIndex.js"></script>
    }

OCC/Views/Guest/_genderBalance.cshtml
@model Models.ViewModels.GenderBalanceViewModel

<div class="ui card">
    <div class="content">
        <div class="header">Gender Balance</div>
        <div class="meta"><i class="refresh icon"></i>@Html.ActionLink("Refresh", "Refresh", "Home")</div>
        <div class="description">
            <a class="ui yellow ribbon label">Invited</a>
            <p>Men: @Model.MenInvited</p>
            <p>Women: @Model.WomenInvited</p>
            <a class="ui green ribbon label">Attending</a>
            <p>Men: @Model.MenAttending</p>
            <p>Women: @Model.WomenAttending</p>
        </div>
    </div>
    <div class="extra content">
        @{if(@Model.InvitedWarning != ""){ 
        <p>
            <i class="warning icon"></i>
            @Model.InvitedWarning
        </p>}}
        @{if(@Model.AttendingWarning != "") {
        <p>
            <i class="warning circle icon"></i>
            @Model.AttendingWarning
        </p>}}
    </div>
</div>

@*<div>
    <h4>GenderBalanceViewModel</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.MenInvited)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MenInvited)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.WomenInvited)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.WomenInvited)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MenAttending)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MenAttending)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.WomenAttending)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.WomenAttending)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.InvitedWarning)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.InvitedWarning)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AttendingWarning)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AttendingWarning)
        </dd>

    </dl>
</div>*@

OCC/Views/Guest/_guestCard.cshtml
@model Guest
@using Models

<div class="card">
    <div class="content">
        <div class="header">@Model.Name @Model.Surname</div>
        <div class="meta">
            <i class="remove user icon"></i>@Html.ActionLink("Remove guest", "Delete", "Guest", new { id = @Model.Id }, null)
            <i class="edit icon"></i>@Html.ActionLink("Edit guest", "Edit", "Guest", new { id = @Model.Id }, null)
        </div>
        <div class="description">
            <div class="ui form">
                <div class="grouped fields">
                    <div class="field">
                        <div class="ui radio checkbox">
                            <input type="radio" name="@Model.Id"
                                   class="@(Model.Status == GuestStatus.Invited ? "checked" : "")">
                            <label data-guest-status="Invited" data-guest-id="@Model.Id" class="guestResponse">Invited</label>
                        </div>
                    </div>
                    <div class="field">
                        <div class="ui radio checkbox">
                            <input type="radio" name="@Model.Id"
                                   class="@(Model.Status == GuestStatus.Attending ? "checked" : "")">
                            <label data-guest-status="Attending" data-guest-id="@Model.Id" class="guestResponse">Attending</label>
                        </div>
                    </div>
                    <div class="field">
                        <div class="ui radio checkbox">
                            <input type="radio" name="@Model.Id"
                                   class="@(Model.Status == GuestStatus.NotAttending ? "checked" : "")">
                            <label data-guest-status="NotAttending" data-guest-id="@Model.Id" class="guestResponse">Not attending</label>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>  

OCC/Views/Home/FailedLoad.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="ui negative message" id="ErrorMessage">
    <i class="close icon" id="CloseErrorMessage"></i>
    <div class="header">
        There was a problem with Loading guests from XML
    </div>
    <p>
        Possibly the file does not exist at destined location. Please use save to XML function first.
    </p>
</div>

@section scripts{
    <script src="~/Scripts/Developer/HomeLoadFailed.js"></script>
}

OCC/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Party Organizer";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2 class="ui header">Party Organizer</h2>

<h3 class="ui header"> hello and welcome,</h3>

<p>
    this is your personal and best party organizer tool.
    here you will be able to input people you have invited for your party,
    you will be able to track their response and also monitor if there is
    roughly the same amount of men and women so everyone can dance and not
    sit alone at your party.
</p>

OCC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Styles.Render("~/Content/SemanticUICss")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jqueryui")    
    @Scripts.Render("~/bundles/siteInitials")
    @Scripts.Render("~/Content/SemanticUIJs")
    @*@Scripts.Render("~/bundles/modernizr")*@
</head>
<body>
    <div class="ui page grid">
        <div class="four wide column">
            @Html.Partial("_LeftMenu")            
        </div>
        <div class="twelve wide column">
            @RenderBody()
        </div>
    </div>       
    
    @RenderSection("scripts", required: false)
    @RenderSection("styles", required: false)
</body>
</html>

OCC/Views/Shared/_LeftMenu.cshtml
<div class="ui vertical menu">
    <div class="ui dropdown item">
        <i class="dropdown icon"></i>
        Party organizer
        <div class="menu">
            @Html.ActionLink("Add guest to the list", "Create", "Guest", null, new { @class = "item" })
            @Html.ActionLink("View Guest list", "Index", "Guest", null, new { @class = "item" })
            @Html.ActionLink("Return to start page", "Index", "Home", null, new { @class = "item"})
        </div>
    </div>
</div>

<div class="ui vertical menu">
    <div class="ui dropdown item">
        <i class="dropdown icon"></i>
        Save/Load XML
        <div class="menu">
            <div id="saveAllGuests" class="item">Save all guests to XML</div>
            <div id="saveAttendingGuests" class="item">Save attending guests to XML</div>            
            @Html.ActionLink("Open all guests from XML", "LoadAllGuests", "Home", null, new { @class = "item" })            
        </div>
    </div>
</div>

@{ Html.RenderAction("GenderBalance", "Guest"); }